// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PoultryFarmSystem.Data;

#nullable disable

namespace PoultryFarmSystem.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PoultryFarmSystem.Models.Entities.Assignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CageId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("WorkerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CageId");

                    b.HasIndex("WorkerId");

                    b.ToTable("Assignments", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CageId = 1,
                            CompletedDate = new DateTime(2024, 11, 13, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            Description = "Полная уборка клетки, дезинфекция кормушек и поилок",
                            EndDate = new DateTime(2024, 11, 13, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            Priority = "Средний",
                            StartDate = new DateTime(2024, 11, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Завершено",
                            Title = "Ежедневная уборка клетки A-50",
                            WorkerId = 3
                        },
                        new
                        {
                            Id = 2,
                            CageId = 1,
                            Description = "Проведение плановой вакцинации от болезни Ньюкасла",
                            EndDate = new DateTime(2024, 11, 14, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            Priority = "Высокий",
                            StartDate = new DateTime(2024, 11, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Выполняется",
                            Title = "Вакцинация кур в клетке A-50",
                            WorkerId = 2
                        },
                        new
                        {
                            Id = 3,
                            CageId = 2,
                            Description = "Проверка системы вентиляции и освещения",
                            EndDate = new DateTime(2024, 11, 15, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            Priority = "Средний",
                            StartDate = new DateTime(2024, 11, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Назначено",
                            Title = "Техническое обслуживание клетки B-75",
                            WorkerId = 5
                        },
                        new
                        {
                            Id = 4,
                            CageId = 3,
                            CompletedDate = new DateTime(2024, 11, 12, 13, 45, 0, 0, DateTimeKind.Unspecified),
                            Description = "Ежедневный сбор и сортировка яиц",
                            EndDate = new DateTime(2024, 11, 12, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Priority = "Низкий",
                            StartDate = new DateTime(2024, 11, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Завершено",
                            Title = "Сбор яиц из клетки C-100",
                            WorkerId = 4
                        },
                        new
                        {
                            Id = 5,
                            CageId = 2,
                            CompletedDate = new DateTime(2024, 11, 14, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            Description = "Утреннее кормление, проверка качества корма",
                            EndDate = new DateTime(2024, 11, 14, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Priority = "Высокий",
                            StartDate = new DateTime(2024, 11, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Завершено",
                            Title = "Кормление уток в клетке B-75",
                            WorkerId = 6
                        },
                        new
                        {
                            Id = 6,
                            CageId = 1,
                            Description = "Осмотр и лечение птицы с признаками заболевания",
                            EndDate = new DateTime(2024, 11, 15, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            Priority = "Критический",
                            StartDate = new DateTime(2024, 11, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Проверяется",
                            Title = "Лечение больной птицы в клетке A-50",
                            WorkerId = 7
                        },
                        new
                        {
                            Id = 7,
                            CageId = 4,
                            Description = "Переучет поголовья и оборудования",
                            EndDate = new DateTime(2024, 11, 16, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            Priority = "Средний",
                            StartDate = new DateTime(2024, 11, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Назначено",
                            Title = "Плановая инвентаризация клетки D-60",
                            WorkerId = 1
                        });
                });

            modelBuilder.Entity("PoultryFarmSystem.Models.Entities.Batch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ArrivalDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("BatchNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Breed")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<DateTime>("HatchDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsArrived")
                        .HasColumnType("bit");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Batches", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArrivalDate = new DateTime(2024, 11, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BatchNumber = "20241115-CHKN-0930",
                            Breed = "Ломан Браун",
                            Count = 1000,
                            HatchDate = new DateTime(2024, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsArrived = true,
                            Source = "Птицефабрика",
                            Type = "Курица"
                        },
                        new
                        {
                            Id = 2,
                            ArrivalDate = new DateTime(2024, 11, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BatchNumber = "20241116-DUCK-1430",
                            Breed = "Пекинская",
                            Count = 500,
                            HatchDate = new DateTime(2024, 11, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsArrived = true,
                            Source = "Ферма",
                            Type = "Утка"
                        },
                        new
                        {
                            Id = 3,
                            BatchNumber = "20241117-TURK-1100",
                            Breed = "Бронзовая",
                            Count = 300,
                            HatchDate = new DateTime(2024, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsArrived = false,
                            Source = "Инкубатор",
                            Type = "Индейка"
                        },
                        new
                        {
                            Id = 4,
                            ArrivalDate = new DateTime(2024, 11, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BatchNumber = "20241118-GOOS-1600",
                            Breed = "Холмогорская",
                            Count = 200,
                            HatchDate = new DateTime(2024, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsArrived = true,
                            Source = "Локальный",
                            Type = "Гусь"
                        },
                        new
                        {
                            Id = 5,
                            ArrivalDate = new DateTime(2024, 11, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BatchNumber = "20241119-QUAIL-0900",
                            Breed = "Японская",
                            Count = 2000,
                            HatchDate = new DateTime(2024, 11, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsArrived = true,
                            Source = "Собственный",
                            Type = "Перепел"
                        },
                        new
                        {
                            Id = 6,
                            BatchNumber = "20241120-CHKN-1400",
                            Breed = "Хайсекс Браун",
                            Count = 800,
                            HatchDate = new DateTime(2024, 11, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsArrived = false,
                            Source = "Импорт",
                            Type = "Курица"
                        },
                        new
                        {
                            Id = 7,
                            ArrivalDate = new DateTime(2024, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BatchNumber = "20241121-DUCK-1030",
                            Breed = "Мускусная",
                            Count = 600,
                            HatchDate = new DateTime(2024, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsArrived = true,
                            Source = "Птицефабрика",
                            Type = "Утка"
                        });
                });

            modelBuilder.Entity("PoultryFarmSystem.Models.Entities.Bird", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BatchId")
                        .HasColumnType("int");

                    b.Property<string>("BirdNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("CageId")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastHealthCheck")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("Weight")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("BatchId");

                    b.HasIndex("CageId");

                    b.ToTable("Birds", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BatchId = 1,
                            BirdNumber = "CHKN-001",
                            CageId = 1,
                            LastHealthCheck = new DateTime(2024, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Активна",
                            Type = "Курица",
                            Weight = 2.5m
                        },
                        new
                        {
                            Id = 2,
                            BatchId = 1,
                            BirdNumber = "CHKN-002",
                            CageId = 1,
                            LastHealthCheck = new DateTime(2024, 11, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Активна",
                            Type = "Курица",
                            Weight = 2.3m
                        },
                        new
                        {
                            Id = 3,
                            BatchId = 1,
                            BirdNumber = "CHKN-003",
                            CageId = 1,
                            LastHealthCheck = new DateTime(2024, 11, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Больна",
                            Type = "Курица",
                            Weight = 2.7m
                        },
                        new
                        {
                            Id = 4,
                            BatchId = 2,
                            BirdNumber = "DUCK-001",
                            CageId = 2,
                            LastHealthCheck = new DateTime(2024, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Активна",
                            Type = "Утка",
                            Weight = 3.2m
                        },
                        new
                        {
                            Id = 5,
                            BatchId = 2,
                            BirdNumber = "DUCK-002",
                            CageId = 2,
                            LastHealthCheck = new DateTime(2024, 11, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Лечение",
                            Type = "Утка",
                            Weight = 3m
                        },
                        new
                        {
                            Id = 6,
                            BatchId = 2,
                            BirdNumber = "DUCK-003",
                            CageId = 2,
                            LastHealthCheck = new DateTime(2024, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Активна",
                            Type = "Утка",
                            Weight = 3.5m
                        },
                        new
                        {
                            Id = 7,
                            BatchId = 3,
                            BirdNumber = "TURK-001",
                            CageId = 3,
                            LastHealthCheck = new DateTime(2024, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Карантин",
                            Type = "Индейка",
                            Weight = 8.2m
                        },
                        new
                        {
                            Id = 8,
                            BatchId = 3,
                            BirdNumber = "TURK-002",
                            CageId = 3,
                            LastHealthCheck = new DateTime(2024, 11, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Активна",
                            Type = "Индейка",
                            Weight = 7.8m
                        },
                        new
                        {
                            Id = 9,
                            BatchId = 3,
                            BirdNumber = "TURK-003",
                            CageId = 3,
                            LastHealthCheck = new DateTime(2024, 11, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Активна",
                            Type = "Индейка",
                            Weight = 9.1m
                        },
                        new
                        {
                            Id = 10,
                            BatchId = 4,
                            BirdNumber = "GOOS-001",
                            CageId = 4,
                            LastHealthCheck = new DateTime(2024, 11, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Активна",
                            Type = "Гусь",
                            Weight = 5.3m
                        },
                        new
                        {
                            Id = 11,
                            BatchId = 4,
                            BirdNumber = "GOOS-002",
                            CageId = 4,
                            LastHealthCheck = new DateTime(2024, 11, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Больна",
                            Type = "Гусь",
                            Weight = 4.9m
                        },
                        new
                        {
                            Id = 12,
                            BatchId = 4,
                            BirdNumber = "GOOS-003",
                            CageId = 4,
                            LastHealthCheck = new DateTime(2024, 10, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Активна",
                            Type = "Гусь",
                            Weight = 5.8m
                        },
                        new
                        {
                            Id = 13,
                            BatchId = 5,
                            BirdNumber = "QUAIL-001",
                            CageId = 5,
                            LastHealthCheck = new DateTime(2024, 11, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Активна",
                            Type = "Перепел",
                            Weight = 0.15m
                        },
                        new
                        {
                            Id = 14,
                            BatchId = 5,
                            BirdNumber = "QUAIL-002",
                            CageId = 5,
                            LastHealthCheck = new DateTime(2024, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Активна",
                            Type = "Перепел",
                            Weight = 0.18m
                        },
                        new
                        {
                            Id = 15,
                            BatchId = 5,
                            BirdNumber = "QUAIL-003",
                            CageId = 5,
                            LastHealthCheck = new DateTime(2024, 11, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Умерла",
                            Type = "Перепел",
                            Weight = 0.16m
                        },
                        new
                        {
                            Id = 16,
                            BatchId = 6,
                            BirdNumber = "CHKN-101",
                            CageId = 6,
                            LastHealthCheck = new DateTime(2024, 11, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Активна",
                            Type = "Курица",
                            Weight = 2.8m
                        },
                        new
                        {
                            Id = 17,
                            BatchId = 6,
                            BirdNumber = "CHKN-102",
                            CageId = 6,
                            LastHealthCheck = new DateTime(2024, 11, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Активна",
                            Type = "Курица",
                            Weight = 2.6m
                        },
                        new
                        {
                            Id = 18,
                            BatchId = 6,
                            BirdNumber = "CHKN-103",
                            CageId = 6,
                            LastHealthCheck = new DateTime(2024, 11, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Лечение",
                            Type = "Курица",
                            Weight = 2.9m
                        },
                        new
                        {
                            Id = 19,
                            BatchId = 7,
                            BirdNumber = "DUCK-101",
                            CageId = 7,
                            LastHealthCheck = new DateTime(2024, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Активна",
                            Type = "Утка",
                            Weight = 3.3m
                        },
                        new
                        {
                            Id = 20,
                            BatchId = 7,
                            BirdNumber = "DUCK-102",
                            CageId = 7,
                            LastHealthCheck = new DateTime(2024, 11, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Карантин",
                            Type = "Утка",
                            Weight = 3.1m
                        },
                        new
                        {
                            Id = 21,
                            BatchId = 7,
                            BirdNumber = "DUCK-103",
                            CageId = 7,
                            LastHealthCheck = new DateTime(2024, 11, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Активна",
                            Type = "Утка",
                            Weight = 3.4m
                        });
                });

            modelBuilder.Entity("PoultryFarmSystem.Models.Entities.Cage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastCleaning")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastMaintenance")
                        .HasColumnType("datetime2");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.HasKey("Id");

                    b.ToTable("Cages", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 50,
                            LastCleaning = new DateTime(2024, 11, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastMaintenance = new DateTime(2024, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "AAA-50",
                            Section = "AAB"
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 75,
                            LastCleaning = new DateTime(2024, 11, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastMaintenance = new DateTime(2024, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "AAC-75",
                            Section = "AAC"
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 100,
                            LastCleaning = new DateTime(2024, 11, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastMaintenance = new DateTime(2024, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "AAD-100",
                            Section = "AAD"
                        },
                        new
                        {
                            Id = 4,
                            Capacity = 60,
                            LastCleaning = new DateTime(2024, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastMaintenance = new DateTime(2024, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "AAE-60",
                            Section = "AAE"
                        },
                        new
                        {
                            Id = 5,
                            Capacity = 120,
                            LastCleaning = new DateTime(2024, 11, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastMaintenance = new DateTime(2024, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "ABA-120",
                            Section = "ABA"
                        },
                        new
                        {
                            Id = 6,
                            Capacity = 80,
                            LastCleaning = new DateTime(2024, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastMaintenance = new DateTime(2024, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "ABC-80",
                            Section = "ABC"
                        },
                        new
                        {
                            Id = 7,
                            Capacity = 90,
                            LastCleaning = new DateTime(2024, 11, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastMaintenance = new DateTime(2024, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "ACA-90",
                            Section = "ACA"
                        });
                });

            modelBuilder.Entity("PoultryFarmSystem.Models.Entities.HealthCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Allergies")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("BirdId")
                        .HasColumnType("int");

                    b.Property<string>("Diseases")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("SpecialNotes")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Vaccinations")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("BirdId")
                        .IsUnique();

                    b.ToTable("HealthCards", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Allergies = "Нет",
                            BirdId = 1,
                            Diseases = "Нет",
                            SpecialNotes = "Здоровая птица, регулярные прививки",
                            Vaccinations = "Ньюкасл, Гамборо, Марек"
                        },
                        new
                        {
                            Id = 2,
                            Allergies = "Нет",
                            BirdId = 2,
                            Diseases = "Легкая простуда в ноябре 2024",
                            SpecialNotes = "Требуется наблюдение после болезни",
                            Vaccinations = "Ньюкасл, Гамборо"
                        },
                        new
                        {
                            Id = 3,
                            Allergies = "Нет",
                            BirdId = 3,
                            Diseases = "Респираторная инфекция",
                            SpecialNotes = "На лечении антибиотиками, изолировать от других птиц",
                            Vaccinations = "Ньюкасл"
                        },
                        new
                        {
                            Id = 4,
                            Allergies = "Нет",
                            BirdId = 4,
                            Diseases = "Нет",
                            SpecialNotes = "Отличное здоровье, активная",
                            Vaccinations = "Грипп птиц, Холера"
                        },
                        new
                        {
                            Id = 5,
                            Allergies = "Нет",
                            BirdId = 5,
                            Diseases = "Травма крыла",
                            SpecialNotes = "Проходит лечение, ограничить движение",
                            Vaccinations = "Грипп птиц"
                        },
                        new
                        {
                            Id = 6,
                            Allergies = "Пыльца",
                            BirdId = 6,
                            Diseases = "Нет",
                            SpecialNotes = "Сезонная аллергия, наблюдать в весенний период",
                            Vaccinations = "Грипп птиц, Холера, Сальмонелла"
                        },
                        new
                        {
                            Id = 7,
                            Allergies = "Нет",
                            BirdId = 7,
                            Diseases = "Кокцидиоз",
                            SpecialNotes = "Карантин, инфекционное заболевание",
                            Vaccinations = "Ньюкасл, Оспа"
                        },
                        new
                        {
                            Id = 8,
                            Allergies = "Нет",
                            BirdId = 8,
                            Diseases = "Нет",
                            SpecialNotes = "Идеальное здоровье, племенная птица",
                            Vaccinations = "Ньюкасл, Оспа, Грипп"
                        },
                        new
                        {
                            Id = 9,
                            Allergies = "Нет",
                            BirdId = 9,
                            Diseases = "Нет",
                            SpecialNotes = "Хорошая физическая форма, быстро набирает вес",
                            Vaccinations = "Ньюкасл, Оспа"
                        });
                });

            modelBuilder.Entity("PoultryFarmSystem.Models.Entities.Worker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Workers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDate = new DateTime(1985, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Иван",
                            HireDate = new DateTime(2020, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            LastName = "Петров",
                            MiddleName = "Сергеевич",
                            Phone = "79123456789",
                            Salary = 85000m,
                            Type = "Руководитель"
                        },
                        new
                        {
                            Id = 2,
                            BirthDate = new DateTime(1990, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Мария",
                            HireDate = new DateTime(2021, 5, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            LastName = "Сидорова",
                            MiddleName = "Ивановна",
                            Phone = "79234567890",
                            Salary = 65000m,
                            Type = "Ветеринар"
                        },
                        new
                        {
                            Id = 3,
                            BirthDate = new DateTime(1992, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Алексей",
                            HireDate = new DateTime(2022, 3, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            LastName = "Кузнецов",
                            Phone = "79345678901",
                            Salary = 35000m,
                            Type = "Уборщик"
                        },
                        new
                        {
                            Id = 4,
                            BirthDate = new DateTime(1988, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Ольга",
                            HireDate = new DateTime(2020, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            LastName = "Васильева",
                            MiddleName = "Петровна",
                            Phone = "+79456789012",
                            Salary = 42000m,
                            Type = "Сборщик"
                        },
                        new
                        {
                            Id = 5,
                            BirthDate = new DateTime(1983, 12, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Дмитрий",
                            HireDate = new DateTime(2019, 11, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = false,
                            LastName = "Николаев",
                            MiddleName = "Александрович",
                            Phone = "+79567890123",
                            Salary = 72000m,
                            Type = "Инженер"
                        },
                        new
                        {
                            Id = 6,
                            BirthDate = new DateTime(1995, 4, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Екатерина",
                            HireDate = new DateTime(2023, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            LastName = "Морозова",
                            MiddleName = "Дмитриевна",
                            Phone = "+79678901234",
                            Salary = 38000m,
                            Type = "Кормильщик"
                        },
                        new
                        {
                            Id = 7,
                            BirthDate = new DateTime(1991, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Сергей",
                            HireDate = new DateTime(2021, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            LastName = "Орлов",
                            MiddleName = "Викторович",
                            Phone = "79789012345",
                            Salary = 68000m,
                            Type = "Ветеринар"
                        });
                });

            modelBuilder.Entity("PoultryFarmSystem.Models.Entities.Assignment", b =>
                {
                    b.HasOne("PoultryFarmSystem.Models.Entities.Cage", "Cage")
                        .WithMany("Assignments")
                        .HasForeignKey("CageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PoultryFarmSystem.Models.Entities.Worker", "Worker")
                        .WithMany("Assignments")
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cage");

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("PoultryFarmSystem.Models.Entities.Bird", b =>
                {
                    b.HasOne("PoultryFarmSystem.Models.Entities.Batch", "Batch")
                        .WithMany("Birds")
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PoultryFarmSystem.Models.Entities.Cage", "Cage")
                        .WithMany("Birds")
                        .HasForeignKey("CageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Batch");

                    b.Navigation("Cage");
                });

            modelBuilder.Entity("PoultryFarmSystem.Models.Entities.HealthCard", b =>
                {
                    b.HasOne("PoultryFarmSystem.Models.Entities.Bird", "Bird")
                        .WithOne("HealthCard")
                        .HasForeignKey("PoultryFarmSystem.Models.Entities.HealthCard", "BirdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bird");
                });

            modelBuilder.Entity("PoultryFarmSystem.Models.Entities.Batch", b =>
                {
                    b.Navigation("Birds");
                });

            modelBuilder.Entity("PoultryFarmSystem.Models.Entities.Bird", b =>
                {
                    b.Navigation("HealthCard")
                        .IsRequired();
                });

            modelBuilder.Entity("PoultryFarmSystem.Models.Entities.Cage", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("Birds");
                });

            modelBuilder.Entity("PoultryFarmSystem.Models.Entities.Worker", b =>
                {
                    b.Navigation("Assignments");
                });
#pragma warning restore 612, 618
        }
    }
}
